version: '3'
services:
  client:
    build: client
    depends_on:
      - datapower
  datapower:
    build: datapower
    tty: true
    stdin_open: true
    depends_on:
      - backend
  backend:
    image: hstenzel/nodejs-hostname-automatic
